name: Update Currency Data

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm install axios
      - name: Run Script
        run: node scripts/updateCurrencyData.js
        env:
          BASE_URL: https://raw.githubusercontent.com/fawazahmed0/currency-api/1/
          BASE_DEST_PATH: ./public/data/
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push changes
        run: |
          git add -A
          git commit -m "Update currency data"
          git push
